#Generated Form Function
function GenerateForm {
    ########################################################################
    # Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
    # Generated On: 9/6/2018 5:23 AM
    # Generated By: Jeff & Damn Daniel
    ########################################################################
    
    #region Import the Assemblies
    [reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
    [reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
    #endregion
    
    #region Generated Form Objects
    $form1 = New-Object System.Windows.Forms.Form
    $button1 = New-Object System.Windows.Forms.Button
    $linkLbl = New-Object System.Windows.Forms.LinkLabel
    $label1 = New-Object System.Windows.Forms.Label
    $pictureBox1 = New-Object System.Windows.Forms.PictureBox
    $InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
    #endregion Generated Form Objects
    
    #----------------------------------------------
    #Generated Event Script Blocks
    #----------------------------------------------
    
    #---------------------------
    #Super Hacker 3000 Methods
    #---------------------------
    function Interwebs{
        param([String]$url)
        Start-Process $url
    }
    #-----------------------------------------------------------------
    #Global variables --- DO NOT OPEN LINKS, USE PROGREM TO OPEN!! 
    #-----------------------------------------------------------------
    # My name Jeff
    $jeff="Jeff"
    $jeffImg="http://i0.kym-cdn.com/entries/icons/original/000/016/894/mynameehhjeff.jpg"
    $jeffVid="https://binged.it/2CnOpYb"
    # Trainer Marcel
    $trainer="TRAINER MARCEL"
    $trainerImg="https://ict.swisscom.ch/wp-content/uploads/2017/09/Marcel-Curien-ct.jpg"
    $trainerVid="https://binged.it/2wO0Qac"
    # suprise
    $supriseArray=@("https://binged.it/2oKcQoN", "https://binged.it/2oMvZXb", 
    "https://binged.it/2oOi6rw", "https://binged.it/2oOGn0N", "https://binged.it/2oNu1Gj",
    "https://binged.it/2oNhH8Z", "https://binged.it/2IqpdOm", "https://binged.it/2wMlkiY",
    "https://binged.it/2wXJDKR", "https://binged.it/2wWfVWE", "https://binged.it/2wZksrf",
    "https://binged.it/2wZxfKx", "https://binged.it/2wYka3R", "https://binged.it/2wXLrUk")
    $qualityContent=@("https://pbs.twimg.com/profile_images/894183755170164736/QgrVY8Ky_400x400.jpg",
    "https://78.media.tumblr.com/fcdb2ee4d5991d3ac542a8637ecac672/tumblr_ooepmiFlNs1t8f4e9o1_400.jpg",
    "https://www.zerohedge.com/sites/default/files/2018-02/sheriff1.JPG", 
    "https://i.ytimg.com/vi/zPOpAjbGP50/hqdefault.jpg", "https://i.ytimg.com/vi/9KxFGpxbolA/maxresdefault.jpg",
    "http://studybreaks.com/wp-content/uploads/2016/03/160222_DX_Damn-Daniel.jpg.CROP_.promo-xlarge2.jpg",
    "https://pmchollywoodlife.files.wordpress.com/2016/02/damn-daniel-rap-ftr.jpg?w=600",
    "https://b.fssta.com/uploads/content/dam/fsdigital/fscom/other/Images/2016/01/13/011316-Celebrity-DJ-Stephen-Hillary-Clinton-Ellen-DeGeneres-PI-JE.vresize.1200.630.high.0.jpg",
    "https://vignette.wikia.nocookie.net/le-miiverse-resource/images/4/45/Sansstop2.png/revision/latest?cb=20161209002419",
    "https://i.redd.it/e7lfx0quph311.jpg", "https://i.kym-cdn.com/photos/images/newsfeed/001/386/508/162.png")
    #----------------------
    # Normal continuation
    #-----------------------
    #Provide Custom Code for events specified in PrimalForms.
    $handler_pictureBox1_Click= 
    {
        Interwebs($supriseArray[(Get-Random -Maximum $supriseArray.Count)])
        $pictureBox1.ImageLocation=$qualityContent[(Get-Random -Maximum $qualityContent.Count)]
        $linkLbl.Text = "???"
    }
    
    $handler_linkLbl_LinkClicked= 
    {
            if ($linkLbl.Text -eq $jeff){
            Interwebs($jeffVid)
        }elseif ($linkLbl.Text -eq $trainer) {
            Interwebs($trainerVid)
        }
    }
    
    $handler_button1_Click= 
    {
        if ($linkLbl.Text -ne $jeff){
            $linkLbl.Text=$jeff
            $pictureBox1.ImageLocation=$jeffImg
        }else{
            $linkLbl.Text=$trainer
            $pictureBox1.ImageLocation=$trainerImg
        }
    }
    
    $OnLoadForm_StateCorrection=
    {#Correct the initial state of the form to prevent the .Net maximized form issue
        $form1.WindowState = $InitialFormWindowState
    }
    
    #----------------------------------------------
    #region Generated Form Code
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 437
    $System_Drawing_Size.Width = 1108
    $form1.ClientSize = $System_Drawing_Size
    $form1.DataBindings.DefaultDataSourceUpdateMode = 0
    $form1.Name = "form1"
    $form1.Text = "NSA Hacker 3000"
#    Bitmap b = (Bitmap)pictureBox1.Image;
#    IntPtr pIcon = b.GetHicon(b);
#    Icon i = Icon.FromHandle(pIcon);
#    this.Icon = i;
#    i.Dispose(i);
#    $form1.Icon="i.imgur.com/Yp8BqRg.png"
    
    
    $button1.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 273
    $System_Drawing_Point.Y = 77
    $button1.Location = $System_Drawing_Point
    $button1.Name = "button1"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 75
    $button1.Size = $System_Drawing_Size
    $button1.TabIndex = 3
    $button1.Text = "is....."
    $button1.UseVisualStyleBackColor = $True
    $button1.add_Click($handler_button1_Click)
    
    $form1.Controls.Add($button1)
    
    $linkLbl.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 341
    $System_Drawing_Point.Y = 51
    $linkLbl.Location = $System_Drawing_Point
    $linkLbl.Name = "linkLbl"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 100
    $linkLbl.Size = $System_Drawing_Size
    $linkLbl.TabIndex = 2
    $linkLbl.TabStop = $True
    $linkLbl.Text = "???"
    $linkLbl.add_LinkClicked($handler_linkLbl_LinkClicked)
    
    $form1.Controls.Add($linkLbl)
    
    $label1.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 273
    $System_Drawing_Point.Y = 51
    $label1.Location = $System_Drawing_Point
    $label1.Name = "label1"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 100
    $label1.Size = $System_Drawing_Size
    $label1.TabIndex = 1
    $label1.Text = "My Name"
    
    $form1.Controls.Add($label1)
    
    
    $pictureBox1.DataBindings.DefaultDataSourceUpdateMode = 0
    
    
    $pictureBox1.ImageLocation = "http://i0.kym-cdn.com/entries/icons/original/000/016/894/mynameehhjeff.jpg"
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 12
    $System_Drawing_Point.Y = 24
    $pictureBox1.Location = $System_Drawing_Point
    $pictureBox1.Name = "pictureBox1"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 401
    $System_Drawing_Size.Width = 247
    $pictureBox1.Size = $System_Drawing_Size
    $pictureBox1.SizeMode = 1
    $pictureBox1.TabIndex = 0
    $pictureBox1.TabStop = $False
    $pictureBox1.add_Click($handler_pictureBox1_Click)
    
    $form1.Controls.Add($pictureBox1)
    
    #endregion Generated Form Code
    
    #Save the initial state of the form
    $InitialFormWindowState = $form1.WindowState
    #Init the OnLoad event to correct the initial state of the form
    $form1.add_Load($OnLoadForm_StateCorrection)
    #Show the Form
    $form1.ShowDialog()| Out-Null
    
    } #End Function
    
    #Call the Function
    GenerateForm
    